PCA/Models/ErrorViewModel.cs
namespace PCA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PCA/Controllers/PermitCheckerController.cs
using Microsoft.AspNetCore.Mvc;
using PermitChecker.Exceptions;
using PermitChecker.Models;
using PermitChecker.Services;

namespace PermitChecker.Controllers
{
    public class PermitCheckerController : Controller
    {
        private readonly IBuildingService _buildingService;
        private readonly IPermissionService _permissionService;
        private readonly IBuildingPermissionViewServices _buildingPermissionViewServices;
        public PermitCheckerController(IBuildingService buildingService, IPermissionService permissionService, IBuildingPermissionViewServices buildingPermissionViewServices)
        {
            _buildingService = buildingService;
            _permissionService = permissionService;
            _buildingPermissionViewServices = buildingPermissionViewServices;
        }
        //Index
        public IActionResult Index()
        {
            return View();
        }
        //Building
        public IActionResult AddBuilding()
        {

            return View();
        }

        [HttpPost]
        public IActionResult AddBuilding(Building building)
        {
            try
            {
                _buildingService.AddBuilding(building);

                return RedirectToAction("Index");
            }
            catch (BadRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
        }

        public IActionResult BuildingList()
        {
            try
            {
                var buildings = _buildingService.GetBuildings();

                return View(buildings);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
        }
        public IActionResult DeleteBuilding(int id)
        {
            try
            {
                _buildingService.RemoveBuilding(id);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }

            return RedirectToAction("Index");
        }

        public IActionResult EditBuilding(int id)
        {
            try
            {
                var building = _buildingService.FindBuilding(id);
                return View(building);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
        }

        [HttpPost]
        public IActionResult EditBuilding(int id, Building editBuilding)
        {
            try
            {
                _buildingService.EditBuilding(id, editBuilding);

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
            catch (BadRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
        }
        public IActionResult BuildingOption()
        {
            return View();
        }

        //Permission
        public IActionResult AddPermission()
        {
            try
            {
                var buildingList = _buildingService.GetBuildings();
                ViewBag.BuildingList = buildingList;
                return View();
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = "Nie można dodać awizacji jesli nie stworzono budynku!";
                return View("ErrorView");
            }



        }

        [HttpPost]
        public IActionResult AddPermission(Permission permission)
        {
            try
            {


                _permissionService.AddPermission(permission);
                return RedirectToAction("Index");
            }

            catch (BadRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
           

        }

        public IActionResult PermissionList()
        {
            _permissionService.Expiration();

            try
            {

                var permissions = _permissionService.GetPermission();

                var buildings = _buildingService.GetBuildings();

                var buildingPermissionViewModels = _buildingPermissionViewServices.TodayPerm(permissions, buildings);

                return View(buildingPermissionViewModels);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }

        }
        public IActionResult DeletePermission(int id)
        {
            try
            {
                _permissionService.RemovePermission(id);

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
        }

        public IActionResult EditPermission(int id)
        {
            try
            {
                var permission = _permissionService.FindPermission(id);
                var buildingList = _buildingService.GetBuildings();
                ViewBag.BuildingList = buildingList;
                return View(permission);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
           




        }

        [HttpPost]
        public IActionResult EditPermission(int id, Permission editPermission)
        {
            try
            {
                _permissionService.EditPermission(id, editPermission);

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
            catch (BadRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
        }

        public IActionResult TodayPermission()
        {
            try
            {
                _permissionService.Expiration();



                var permissions = _permissionService.IsPermissionValidToday();

                var buildings = _buildingService.GetBuildings();

                var buildingPermissionViewModels = _buildingPermissionViewServices.TodayPerm(permissions, buildings);

                return View(buildingPermissionViewModels);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }
            catch (BadRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["ErrorMessage"] = ex.Message;
                return View("ErrorView");
            }

        }

        
    }
}

PCA/Views/PermitChecker/AddBuilding.cshtml
@using PermitChecker.Models;


@model Building

@using (Html.BeginForm("AddBuilding", "PermitChecker", FormMethod.Post))

{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Your Razor Page</title>
        <link rel="stylesheet" href="~/css/mystyles.css" asp-append-version="true" />
        <style>

            #panel {
                width: 400px;
                margin: 0 auto;
                padding: 15px 0 0;
                background: #fff;
                border: 1px solid silver;
                font: 16px calibri;
                letter-spacing: -1px;
                -webkit-box-shadow: 0 0 2px silver;
                -moz-box-shadow: 0 0 2px silver;
                box-shadow: 0 0 2px silver;
            }

            label {
                display: block;
                width: 260px;
                padding: 10px 20px;
                color: #696969;
                font-size: 16px;
                text-shadow: 0 0 1px silver;
            }

            #name {
                display: block;
                width: 360px;
                margin: 0 auto;
                padding: 10px 5px;
                border: 1px solid silver;
                outline: 5px solid #ebebeb;
                font-size: 22px;
            }

                #name:focus {
                    outline: 5px solid #e5f2f8;
                }

            #lower {
                background: #ecf2f5;
                width: 100%;
                padding: 5px 20px;
                margin-top: 20px;
            }



            input[type="submit"] {
                width: 70px;
                padding: 5px 13px;
                border: 1px solid #005f85;
                color: white;
                text-shadow: 0 0 1px black;
                background: #98c9dc;
                position: left;
                left: 180px;
            }

            #panel, input[type="submit"] {
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
            }

        </style>
    </head>
    <body>
        <div id="panel">
            <form>

                <center><b>Dodaj Nowy Budynek</b></center>

                @Html.LabelFor(model => model.Name, "Nazwa Budynku")
                @Html.TextBoxFor(model => model.Name, new {type = "text", id = "name"})


                <div id="lower">

                    <input type="submit" value="Dodaj">
                </div>
            </form>
        </div>
    </body>
    </html>
}

PCA/Views/PermitChecker/AddPermission.cshtml
@using PermitChecker.Models;


@model Permission

@using (Html.BeginForm("AddPermission", "PermitChecker", FormMethod.Post))

{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Your Razor Page</title>
        <link rel="stylesheet" href="~/css/mystyles.css" asp-append-version="true" />
        <style>

            #panel {
                width: 400px;
                margin: 0 auto;
                padding: 15px 0 0;
                background: #fff;
                border: 1px solid silver;
                font: 16px calibri;
                letter-spacing: -1px;
                -webkit-box-shadow: 0 0 2px silver;
                -moz-box-shadow: 0 0 2px silver;
                box-shadow: 0 0 2px silver;
            }

            label {
                display: block;
                width: 260px;
                padding: 10px 20px;
                color: #696969;
                font-size: 16px;
                text-shadow: 0 0 1px silver;
            }

            #place, #company, #rangeOfHours, #startDate, #endDate, #description, #asist, #building {
                display: block;
                width: 360px;
                margin: 0 auto;
                padding: 10px 5px;
                border: 1px solid silver;
                outline: 5px solid #ebebeb;
                font-size: 22px;
            }

                #place:focus, #company:focus, #rangeOfHours:focus, #startDate:focus, #endDate:focus, #description:focus, #asist:focus, #building:focus {
                    outline: 5px solid #e5f2f8;
                }

            #lower {
                background: #ecf2f5;
                width: 100%;
                padding: 5px 20px;
                margin-top: 20px;
            }



            input[type="submit"] {
                width: 70px;
                padding: 5px 13px;
                border: 1px solid #005f85;
                color: white;
                text-shadow: 0 0 1px black;
                background: #98c9dc;
                position: left;
                left: 180px;
            }

            #panel, input[type="submit"] {
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
            }

        </style>
    </head>
    <body>
        <div id="panel">
            <form>

                <center><b>Dodaj Nową Awizacje</b></center>

                @Html.LabelFor(model => model.Place, "Miejsce Wykonywania Prac")
                @Html.TextBoxFor(model => model.Place, new {type = "text", id = "place"})

                @Html.LabelFor(model => model.Company, "Firma Wykonująca Prace")
                @Html.TextBoxFor(model => model.Company, new {type = "text", id = "company"})

                @Html.LabelFor(model => model.RangeOfHours, "Zakres Godzin")
                @Html.TextBoxFor(model => model.RangeOfHours, new {type = "text", id = "rangeOfHours"})

                @Html.LabelFor(model => model.StartDate, "Data Rozpoczęcia")
                @Html.TextBoxFor(model => model.StartDate,"{0:yyyy-MM-dd}", new {type = "date", id = "startDate"})

                @Html.LabelFor(model => model.EndDate, "Data Zakończenia")
                @Html.TextBoxFor(model => model.EndDate, "{0:yyyy-MM-dd}", new {type = "date", id = "endDate"})


                @Html.LabelFor(model => model.Description, "Rodzaj Wykonywanych Prac")
                @Html.TextBoxFor(model => model.Description, new {type = "text", id = "description"})

                @Html.LabelFor(model => model.Asist, "Czy Potrzeba Asysty")
                <select id="asist" name="Asist">
                    <option value="Tak">Tak</option>
                    <option value="Nie">Nie</option>
                </select>
               

                @Html.LabelFor(model => model.BuildingID, "Wybierz Budynek")
                <select id="building" name="BuildingId">
                    @foreach (var building in ViewBag.BuildingList)
                    {
                        <option value="@building.Id" data-buildingname="@building.Name">@building.Name</option>
                    }
                </select>









                <div id="lower">

                    <input type="submit" value="Dodaj">
                </div>
            </form>
        </div>
    </body>
    </html>
}

PCA/Views/PermitChecker/BuildingList.cshtml
@using PermitChecker.Models;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Your Razor Page</title>
    <link rel="stylesheet" href="~/css/mystyles.css" asp-append-version="true" />
    <style>

        #panel {
            width: 100%;
            margin: 0 auto;
            padding: 15px 0 0;
            background: #fff;
            border: 1px solid silver;
            font: 16px calibri;
            letter-spacing: -1px;
            -webkit-box-shadow: 0 0 2px silver;
            -moz-box-shadow: 0 0 2px silver;
            box-shadow: 0 0 2px silver;
        }

        label {
            display: block;
            width: 260px;
            padding: 10px 20px;
            color: #696969;
            font-size: 16px;
            text-shadow: 0 0 1px silver;
        }






        .button {
            display: inline-block;
            padding: 10px 20px;
            background: #98c9dc;
            border: 1px solid #005f85;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            cursor: pointer;
            text-align: center;
            width: 100%;
            text-shadow: 0 0 1px black;
        }

            .button:hover {
                background: #98c9dc;
                border: 1px solid #005f85;
                color: white;
                text-decoration: none;
                border-radius: 5px;
                cursor: pointer;
                text-align: center;
                width: 100%;
                text-shadow: 0 0 1px black;
            }



        #panel {
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
        }

    </style>
</head>
<body>
    <div id="panel">
        <form>

            <table class="table">
                <thead>
                    <tr>

                        <th>Lista Budynków</th>

                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>

                    @model List<Building>

                    @foreach (var building in Model)
                    {
                        <tr>

                            <th>@building.Name</th>

                            <th><a href="@Url.Action("DeleteBuilding", "PermitChecker", new { id = building.Id })" class="button">Usuń Budyenk</a></th>
                            <th><a href="@Url.Action("EditBuilding", "PermitChecker", new { id = building.Id })" class="button">Edytuj Budynek</a></th>
                        </tr>
                    }
                </tbody>
            </table>
        </form>
    </div>
</body>
</html>

PCA/Views/PermitChecker/BuildingOption.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Your Razor Page</title>
    <style>
        #panel {
            width: 20%;
            margin: 0 auto;
            padding: 15px 0 0;
            background: #fff;
            border: 1px solid silver;
            font: 16px calibri;
            letter-spacing: -1px;
            -webkit-box-shadow: 0 0 2px silver;
            -moz-box-shadow: 0 0 2px silver;
            box-shadow: 0 0 2px silver;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background: #98c9dc;
            border: 1px solid #005f85;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            cursor: pointer;
            text-align: center;
            width: 100px;
            text-shadow: 0 0 1px black;
            margin: 10px 0; /* Odstęp między przyciskami */
        }

            .button:hover {
                background: #98c9dc;
                border: 1px solid #005f85;
                color: white;
                text-decoration: none;
                border-radius: 5px;
                cursor: pointer;
                text-align: center;
                width: 100px;
                text-shadow: 0 0 1px black;
            }

        #panel {
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div id="panel">
        <form>
            <div class="button-container">
                <a href="@Url.Action("AddBuilding", "PermitChecker")" class="button">Dodaj Budynek</a>
                <a href="@Url.Action("BuildingList", "PermitChecker")" class="button">Lista Budynków</a>
              
            </div>
        </form>
    </div>
</body>
</html>

PCA/Views/PermitChecker/EditBuilding.cshtml
@using PermitChecker.Models;


@model Building

@using (Html.BeginForm("EditBuilding", "PermitChecker", FormMethod.Post))

{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Your Razor Page</title>
        <link rel="stylesheet" href="~/css/mystyles.css" asp-append-version="true" />
        <style>

            #panel {
                width: 400px;
                margin: 0 auto;
                padding: 15px 0 0;
                background: #fff;
                border: 1px solid silver;
                font: 16px calibri;
                letter-spacing: -1px;
                -webkit-box-shadow: 0 0 2px silver;
                -moz-box-shadow: 0 0 2px silver;
                box-shadow: 0 0 2px silver;
            }

            label {
                display: block;
                width: 260px;
                padding: 10px 20px;
                color: #696969;
                font-size: 16px;
                text-shadow: 0 0 1px silver;
            }

            #name {
                display: block;
                width: 360px;
                margin: 0 auto;
                padding: 10px 5px;
                border: 1px solid silver;
                outline: 5px solid #ebebeb;
                font-size: 22px;
            }

                #name:focus {
                    outline: 5px solid #e5f2f8;
                }

            #lower {
                background: #ecf2f5;
                width: 100%;
                padding: 5px 20px;
                margin-top: 20px;
            }



            input[type="submit"] {
                width: 70px;
                padding: 5px 13px;
                border: 1px solid #005f85;
                color: white;
                text-shadow: 0 0 1px black;
                background: #98c9dc;
                position: left;
                left: 180px;
            }

            #panel, input[type="submit"] {
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
            }

        </style>
    </head>
    <body>
        <div id="panel">
            <form>

                <center><b>Edytuj Budynek</b></center>

                @Html.LabelFor(model => model.Name, "Nowa Nazwa Budynku")
                @Html.TextBoxFor(model => model.Name, new {type = "text", id = "name"})


                <div id="lower">

                    <input type="submit" value="Edytuj">
                </div>
            </form>
        </div>
    </body>
    </html>
}

PCA/Views/PermitChecker/EditPermission.cshtml
@using PermitChecker.Models;


@model Permission

@using (Html.BeginForm("EditPermission", "PermitChecker", FormMethod.Post))

{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Your Razor Page</title>
        <link rel="stylesheet" href="~/css/mystyles.css" asp-append-version="true" />
        <style>

            #panel {
                width: 400px;
                margin: 0 auto;
                padding: 15px 0 0;
                background: #fff;
                border: 1px solid silver;
                font: 16px calibri;
                letter-spacing: -1px;
                -webkit-box-shadow: 0 0 2px silver;
                -moz-box-shadow: 0 0 2px silver;
                box-shadow: 0 0 2px silver;
            }

            label {
                display: block;
                width: 260px;
                padding: 10px 20px;
                color: #696969;
                font-size: 16px;
                text-shadow: 0 0 1px silver;
            }

            #place, #company, #rangeOfHours, #startDate, #endDate, #description, #asist, #building {
                display: block;
                width: 360px;
                margin: 0 auto;
                padding: 10px 5px;
                border: 1px solid silver;
                outline: 5px solid #ebebeb;
                font-size: 22px;
            }

                #place:focus, #company:focus, #rangeOfHours:focus, #startDate:focus, #endDate:focus, #description:focus, #asist:focus, #building:focus {
                    outline: 5px solid #e5f2f8;
                }

            #lower {
                background: #ecf2f5;
                width: 100%;
                padding: 5px 20px;
                margin-top: 20px;
            }



            input[type="submit"] {
                width: 70px;
                padding: 5px 13px;
                border: 1px solid #005f85;
                color: white;
                text-shadow: 0 0 1px black;
                background: #98c9dc;
                position: left;
                left: 180px;
            }

            #panel, input[type="submit"] {
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
            }

        </style>
    </head>
    <body>
        <div id="panel">
            <form>

                <center><b>Edytuj Awizacje</b></center>

                @Html.LabelFor(model => model.Place, "Miejsce Wykonywania Prac")
                @Html.TextBoxFor(model => model.Place, new {type = "text", id = "place"})

                @Html.LabelFor(model => model.Company, "Firma Wykonująca Prace")
                @Html.TextBoxFor(model => model.Company, new {type = "text", id = "company"})

                @Html.LabelFor(model => model.RangeOfHours, "Zakres Godzin")
                @Html.TextBoxFor(model => model.RangeOfHours, new {type = "text", id = "rangeOfHours"})

                @Html.LabelFor(model => model.StartDate, "Data Rozpoczęcia")
                @Html.TextBoxFor(model => model.StartDate, "{0:yyyy-MM-dd}",  new {type = "date", id = "startDate"})

                @Html.LabelFor(model => model.EndDate, "Data Zakończenia")
                @Html.TextBoxFor(model => model.EndDate, "{0:yyyy-MM-dd}",  new {type = "date", id = "endDate"})

                @Html.LabelFor(model => model.Description, "Rodzaj Wykonywanych Prac")
                @Html.TextBoxFor(model => model.Description, new {type = "text", id = "description"})

                @Html.LabelFor(model => model.Asist, "Czy Potrzeba Asysty")
                <select id="asist" name="Asist">
                    <option value="Tak">Tak</option>
                    <option value="Nie">Nie</option>
                </select>


                @Html.LabelFor(model => model.BuildingID, "Wybierz Budynek")
                <select id="building" name="BuildingName">
                    @foreach (var building in ViewBag.BuildingList)
                    {

                        <option value="@building.Name">@building.Name</option>
                    }
                </select>









                <div id="lower">

                    <input type="submit" value="Edytuj">
                </div>
            </form>
        </div>
    </body>
    </html>
}

PCA/Views/PermitChecker/ErrorView.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Your Razor Page</title>
    <link rel="stylesheet" href="~/css/mystyles.css" asp-append-version="true" />
    <style>

        #panel {
            width: 400px;
            margin: 0 auto;
            padding: 15px 0 0;
            background: #fff;
            border: 1px solid silver;
            font: 16px calibri;
            letter-spacing: -1px;
            -webkit-box-shadow: 0 0 2px silver;
            -moz-box-shadow: 0 0 2px silver;
            box-shadow: 0 0 2px silver;
        }






        #lower {
            background: #ecf2f5;
            width: 100%;
            padding: 5px 20px;
            margin-top: 20px;
        }

    </style>
</head>
<body>
    <div id="panel">
        <form>


            <center><b>An error occurred</b></center>

            <div id="lower">


                <center><b>@ViewData["ErrorMessage"]</b></center>

            </div>
        </form>
    </div>
</body>
</html>

PCA/Views/PermitChecker/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}